### PR TITLE
Fix generateJSONs

### PR DESCRIPTION
**Pull request by MrVauxs**
Given you deleted the change I made from jb2aFreeDatabase, I will just do the same method as the module

### CODE REVIEW

**Comment by Jules-Bens-Aa** [comment]
I think it was intended from our part. Could you point us to the deleted part ?

**Comment by MrVauxs** [comment]
> I think it was intended from our part. Could you point us to the deleted part ?

It was right at the end, `return databasePaths`.

This PR makes that change irrelevant, so feel free to merge it.

**Comment by BenIsWassily** [comment]
Sorry ! Jules made me realise that I didn't mean it that way. I meant that it wasn't intentional. Does our change penalise you in any way ?

**Comment by MrVauxs** [comment]
Nope!

**Comment by BenIsWassily** [comment]
Cool !

**Pull request merged**
